name: validator
version: 0.0.7
author: Karan Goel <karan@goel.io>
description: String validation and sanitization for Dart.
homepage: https://github.com/karan/validator.dart
documentation: https://github.com/karan/validator.dart
# dependencies:
#   unittest: any
environment:
  sdk: '>=1.19.0 <3.0.0'
